services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    build: .
    command: sh -c "composer install && php -S lumen:8000 -t public"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=lumen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
